import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as apigateway from 'aws-cdk-lib/aws-apigateway';
import * as opensearchserverless from 'aws-cdk-lib/aws-opensearchserverless';
import * as kms from 'aws-cdk-lib/aws-kms';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as ssm from 'aws-cdk-lib/aws-ssm';
import * as wafv2 from 'aws-cdk-lib/aws-wafv2';
import * as cr from 'aws-cdk-lib/custom-resources';
import * as cognito from 'aws-cdk-lib/aws-cognito';
import * as sqs from 'aws-cdk-lib/aws-sqs';
import * as lambdaEventSources from 'aws-cdk-lib/aws-lambda-event-sources';
import * as s3n from 'aws-cdk-lib/aws-s3-notifications';
import * as path from 'path';
import { Duration, RemovalPolicy, Stack, StackProps } from 'aws-cdk-lib';

export interface AskMyDocsStackProps extends StackProps {
  allowedOrigins?: string;
  maxFileSizeMb?: number;
  enableWaf?: boolean;
}

export class AskMyDocsStack extends cdk.Stack {
  public readonly apiUrl: cdk.CfnOutput;
  public readonly bucketName: cdk.CfnOutput;
  public readonly userPoolId: cdk.CfnOutput;
  public readonly userPoolClientId: cdk.CfnOutput;

  constructor(scope: Construct, id: string, props: AskMyDocsStackProps = {}) {
    super(scope, id, props);

    const { allowedOrigins = '*', maxFileSizeMb = 50, enableWaf = true } = props;

    // ─────────────────────────────────────────────────────────────────────────
    // 1. KMS Customer-Managed Key
    //    Used to encrypt S3, SSM parameters, CloudWatch Logs, and SQS.
    //    Key rotation is enabled to satisfy compliance baselines.
    // ─────────────────────────────────────────────────────────────────────────
    const encryptionKey = new kms.Key(this, 'EncryptionKey', {
      description: 'ask-my-docs encryption key',
      enableKeyRotation: true,
      removalPolicy: RemovalPolicy.DESTROY, // change to RETAIN for production
    });

    // ─────────────────────────────────────────────────────────────────────────
    // 2. S3 Bucket – PDF Storage
    //    Block all public access. SSE-KMS with CMK. Versioning + access logging.
    // ─────────────────────────────────────────────────────────────────────────
    const accessLogsBucket = new s3.Bucket(this, 'AccessLogsBucket', {
      encryption: s3.BucketEncryption.S3_MANAGED,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      versioned: false,
      removalPolicy: RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
      lifecycleRules: [{ expiration: Duration.days(90) }],
    });

    const pdfBucket = new s3.Bucket(this, 'PdfBucket', {
      encryption: s3.BucketEncryption.KMS,
      encryptionKey,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      versioned: true,
      enforceSSL: true,
      serverAccessLogsBucket: accessLogsBucket,
      serverAccessLogsPrefix: 'pdf-bucket-access/',
      removalPolicy: RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
      cors: [], // No public CORS – uploads go through signed URLs generated by backend
      lifecycleRules: [
        {
          id: 'delete-old-versions',
          noncurrentVersionExpiration: Duration.days(30),
        },
        {
          id: 'expire-objects',
          expiration: Duration.days(365),
        },
      ],
    });

    // Bucket policy: Deny any unencrypted PUT
    pdfBucket.addToResourcePolicy(new iam.PolicyStatement({
      sid: 'DenyUnencryptedObjectUploads',
      effect: iam.Effect.DENY,
      principals: [new iam.AnyPrincipal()],
      actions: ['s3:PutObject'],
      resources: [`${pdfBucket.bucketArn}/*`],
      conditions: {
        StringNotEquals: {
          's3:x-amz-server-side-encryption': 'aws:kms',
        },
      },
    }));

    // ─────────────────────────────────────────────────────────────────────────
    // 3. SQS Queue – Reliable Ingest Pipeline
    //    Decouples S3 events from Lambda. DLQ captures failed messages.
    // ─────────────────────────────────────────────────────────────────────────
    const ingestDlq = new sqs.Queue(this, 'IngestDlq', {
      queueName: 'ask-my-docs-ingest-dlq',
      encryptionMasterKey: encryptionKey,
      retentionPeriod: Duration.days(14),
    });

    const ingestQueue = new sqs.Queue(this, 'IngestQueue', {
      queueName: 'ask-my-docs-ingest',
      encryptionMasterKey: encryptionKey,
      visibilityTimeout: Duration.seconds(360), // 6× Lambda timeout
      deadLetterQueue: { queue: ingestDlq, maxReceiveCount: 3 },
    });

    // Allow S3 to send messages to the queue
    ingestQueue.addToResourcePolicy(new iam.PolicyStatement({
      sid: 'AllowS3SendMessage',
      effect: iam.Effect.ALLOW,
      principals: [new iam.ServicePrincipal('s3.amazonaws.com')],
      actions: ['sqs:SendMessage'],
      resources: [ingestQueue.queueArn],
      conditions: {
        ArnLike: { 'aws:SourceArn': pdfBucket.bucketArn },
      },
    }));

    // ─────────────────────────────────────────────────────────────────────────
    // 4. OpenSearch Serverless Collection
    //    Encryption, network, and data access policies are all separate
    //    CfnResource constructs so that CDK can resolve IAM role ARNs
    //    dynamically at synth time – no manual ARN copy-paste required.
    // ─────────────────────────────────────────────────────────────────────────
    const collectionName = 'ask-my-docs';

    const encryptionPolicy = new opensearchserverless.CfnSecurityPolicy(this, 'AossEncryptionPolicy', {
      name: 'ask-my-docs-enc',
      type: 'encryption',
      policy: JSON.stringify({
        Rules: [{ Resource: [`collection/${collectionName}`], ResourceType: 'collection' }],
        AWSOwnedKey: true,
      }),
    });

    const networkPolicy = new opensearchserverless.CfnSecurityPolicy(this, 'AossNetworkPolicy', {
      name: 'ask-my-docs-net',
      type: 'network',
      policy: JSON.stringify([{
        Rules: [
          { Resource: [`collection/${collectionName}`], ResourceType: 'collection' },
          { Resource: [`collection/${collectionName}`], ResourceType: 'dashboard' },
        ],
        AllowFromPublic: false, // VPC endpoint required for production; set true for demo
      }]),
    });

    const aossCollection = new opensearchserverless.CfnCollection(this, 'AossCollection', {
      name: collectionName,
      type: 'VECTORSEARCH',
      description: 'Vector index for Ask My Docs RAG pipeline',
    });
    aossCollection.addDependency(encryptionPolicy);
    aossCollection.addDependency(networkPolicy);

    // ─────────────────────────────────────────────────────────────────────────
    // 5. Lambda Execution Roles – Least Privilege
    //    Two separate roles: one for ingest, one for query.
    //    Neither can perform actions belonging to the other.
    // ─────────────────────────────────────────────────────────────────────────

    // --- Ingest Role ---
    const ingestRole = new iam.Role(this, 'IngestLambdaRole', {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      description: 'Execution role for ask-my-docs ingest Lambda',
    });

    // CloudWatch Logs
    ingestRole.addToPolicy(new iam.PolicyStatement({
      sid: 'Logs',
      actions: ['logs:CreateLogGroup', 'logs:CreateLogStream', 'logs:PutLogEvents'],
      resources: [`arn:aws:logs:${this.region}:${this.account}:log-group:/aws/lambda/ask-my-docs-ingest*`],
    }));
    // X-Ray
    ingestRole.addToPolicy(new iam.PolicyStatement({
      sid: 'XRay',
      actions: ['xray:PutTraceSegments', 'xray:PutTelemetryRecords'],
      resources: ['*'],
    }));
    // S3 read only on PDF bucket
    ingestRole.addToPolicy(new iam.PolicyStatement({
      sid: 'S3ReadPdfs',
      actions: ['s3:GetObject', 's3:GetObjectVersion'],
      resources: [`${pdfBucket.bucketArn}/*`],
    }));
    // SQS receive/delete for ingest queue
    ingestRole.addToPolicy(new iam.PolicyStatement({
      sid: 'SqsIngest',
      actions: ['sqs:ReceiveMessage', 'sqs:DeleteMessage', 'sqs:GetQueueAttributes'],
      resources: [ingestQueue.queueArn],
    }));
    // Bedrock – Titan Embeddings only
    ingestRole.addToPolicy(new iam.PolicyStatement({
      sid: 'BedrockTitanEmbed',
      actions: ['bedrock:InvokeModel'],
      resources: [`arn:aws:bedrock:${this.region}::foundation-model/amazon.titan-embed-text-v1`],
    }));
    // OpenSearch Serverless – write operations only
    ingestRole.addToPolicy(new iam.PolicyStatement({
      sid: 'AossWrite',
      actions: ['aoss:APIAccessAll'],
      resources: [aossCollection.attrArn],
    }));
    // KMS decrypt (for reading S3 objects encrypted with CMK)
    encryptionKey.grantDecrypt(ingestRole);
    // SSM read for config parameters
    ingestRole.addToPolicy(new iam.PolicyStatement({
      sid: 'SsmRead',
      actions: ['ssm:GetParameter', 'ssm:GetParameters'],
      resources: [`arn:aws:ssm:${this.region}:${this.account}:parameter/ask-my-docs/*`],
    }));

    // --- Query Role ---
    const queryRole = new iam.Role(this, 'QueryLambdaRole', {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
      description: 'Execution role for ask-my-docs query Lambda',
    });

    queryRole.addToPolicy(new iam.PolicyStatement({
      sid: 'Logs',
      actions: ['logs:CreateLogGroup', 'logs:CreateLogStream', 'logs:PutLogEvents'],
      resources: [`arn:aws:logs:${this.region}:${this.account}:log-group:/aws/lambda/ask-my-docs-query*`],
    }));
    queryRole.addToPolicy(new iam.PolicyStatement({
      sid: 'XRay',
      actions: ['xray:PutTraceSegments', 'xray:PutTelemetryRecords'],
      resources: ['*'],
    }));
    // Bedrock – Titan Embeddings + Claude Haiku only
    queryRole.addToPolicy(new iam.PolicyStatement({
      sid: 'BedrockInfer',
      actions: ['bedrock:InvokeModel'],
      resources: [
        `arn:aws:bedrock:${this.region}::foundation-model/amazon.titan-embed-text-v1`,
        `arn:aws:bedrock:${this.region}::foundation-model/anthropic.claude-3-haiku-20240307-v1:0`,
      ],
    }));
    // OpenSearch Serverless – read operations only
    queryRole.addToPolicy(new iam.PolicyStatement({
      sid: 'AossRead',
      actions: ['aoss:APIAccessAll'],
      resources: [aossCollection.attrArn],
    }));
    queryRole.addToPolicy(new iam.PolicyStatement({
      sid: 'SsmRead',
      actions: ['ssm:GetParameter', 'ssm:GetParameters'],
      resources: [`arn:aws:ssm:${this.region}:${this.account}:parameter/ask-my-docs/*`],
    }));

    // ─────────────────────────────────────────────────────────────────────────
    // 6. AOSS Data Access Policy
    //    Resolves role ARNs at CDK synth time. No manual copy-paste needed.
    // ─────────────────────────────────────────────────────────────────────────
    const dataAccessPolicy = new opensearchserverless.CfnAccessPolicy(this, 'AossDataAccessPolicy', {
      name: 'ask-my-docs-dap',
      type: 'data',
      policy: JSON.stringify([
        {
          Rules: [
            {
              ResourceType: 'index',
              Resource: [`index/${collectionName}/*`],
              Permission: [
                'aoss:CreateIndex',
                'aoss:UpdateIndex',
                'aoss:WriteDocument',
                'aoss:ReadDocument',
                'aoss:DescribeIndex',
              ],
            },
          ],
          Principal: [ingestRole.roleArn],
          Description: 'Ingest Lambda – write access',
        },
        {
          Rules: [
            {
              ResourceType: 'index',
              Resource: [`index/${collectionName}/*`],
              Permission: [
                'aoss:ReadDocument',
                'aoss:DescribeIndex',
              ],
            },
          ],
          Principal: [queryRole.roleArn],
          Description: 'Query Lambda – read-only access',
        },
      ]),
    });
    dataAccessPolicy.addDependency(aossCollection);

    // ─────────────────────────────────────────────────────────────────────────
    // 7. SSM Parameters – Configuration (never plaintext env vars)
    // ─────────────────────────────────────────────────────────────────────────
    const collectionEndpointParam = new ssm.StringParameter(this, 'CollectionEndpointParam', {
      parameterName: '/ask-my-docs/collection-endpoint',
      stringValue:   aossCollection.attrCollectionEndpoint,
      description:   'OpenSearch Serverless collection endpoint',
    });

    const indexNameParam = new ssm.StringParameter(this, 'IndexNameParam', {
      parameterName: '/ask-my-docs/index-name',
      stringValue:   'ask-my-docs',
      description:   'OpenSearch index name',
    });

    const regionParam = new ssm.StringParameter(this, 'RegionParam', {
      parameterName: '/ask-my-docs/region',
      stringValue:   this.region,
    });

    // ─────────────────────────────────────────────────────────────────────────
    // 8. Lambda Functions
    // ─────────────────────────────────────────────────────────────────────────
    const commonLambdaProps = {
      runtime: lambda.Runtime.PYTHON_3_12,
      tracing: lambda.Tracing.ACTIVE,
      logRetention: logs.RetentionDays.ONE_MONTH,
      environment: {
        POWERTOOLS_SERVICE_NAME: 'ask-my-docs',
        POWERTOOLS_LOG_LEVEL:    'INFO',
        COLLECTION_ENDPOINT_PARAM: '/ask-my-docs/collection-endpoint',
        INDEX_NAME_PARAM:          '/ask-my-docs/index-name',
        REGION_PARAM:              '/ask-my-docs/region',
        MAX_FILE_SIZE_MB:          String(maxFileSizeMb),
      },
    };

    const ingestLambda = new lambda.Function(this, 'IngestLambda', {
      ...commonLambdaProps,
      functionName: 'ask-my-docs-ingest',
      handler:      'handler.handler',
      code:         lambda.Code.fromAsset(path.join(__dirname, '../../lambdas/ingest'), {
        bundling: {
          image:   lambda.Runtime.PYTHON_3_12.bundlingImage,
          command: [
            'bash', '-c',
            'pip install -r requirements.txt -t /asset-output && cp -r . /asset-output',
          ],
        },
      }),
      role:         ingestRole,
      timeout:      Duration.seconds(300),
      memorySize:   512,
      description:  'Chunks PDF, embeds with Titan, indexes in AOSS',
    });

    const queryLambda = new lambda.Function(this, 'QueryLambda', {
      ...commonLambdaProps,
      functionName:        'ask-my-docs-query',
      handler:             'handler.handler',
      code:                lambda.Code.fromAsset(path.join(__dirname, '../../lambdas/query'), {
        bundling: {
          image:   lambda.Runtime.PYTHON_3_12.bundlingImage,
          command: [
            'bash', '-c',
            'pip install -r requirements.txt -t /asset-output && cp -r . /asset-output',
          ],
        },
      }),
      role:                queryRole,
      timeout:             Duration.seconds(30),
      memorySize:          256,
      reservedConcurrentExecutions: 20,
      description:         'Embeds query, searches AOSS, generates answer via Claude',
    });

    // S3 → SQS → ingest Lambda event source
    pdfBucket.addEventNotification(
      s3.EventType.OBJECT_CREATED,
      new s3n.SqsDestination(ingestQueue),
      { suffix: '.pdf' },
    );
    ingestLambda.addEventSource(new lambdaEventSources.SqsEventSource(ingestQueue, {
      batchSize: 1,
      enabled:   true,
    }));

    // ─────────────────────────────────────────────────────────────────────────
    // 9. Cognito User Pool – Authentication
    // ─────────────────────────────────────────────────────────────────────────
    const userPool = new cognito.UserPool(this, 'UserPool', {
      userPoolName:     'ask-my-docs-users',
      selfSignUpEnabled: false,
      signInAliases:    { email: true },
      passwordPolicy: {
        minLength:        12,
        requireLowercase: true,
        requireUppercase: true,
        requireDigits:    true,
        requireSymbols:   true,
      },
      accountRecovery:  cognito.AccountRecovery.EMAIL_ONLY,
      removalPolicy:    RemovalPolicy.DESTROY,
    });

    const userPoolClient = new cognito.UserPoolClient(this, 'UserPoolClient', {
      userPool,
      generateSecret: false,
      authFlows: { userSrp: true },
    });

    const cognitoAuthorizer = new apigateway.CognitoUserPoolsAuthorizer(this, 'CognitoAuthorizer', {
      cognitoUserPools: [userPool],
    });

    // ─────────────────────────────────────────────────────────────────────────
    // 10. API Gateway REST API
    //     Cognito authorizer, request validation, throttling, logging
    // ─────────────────────────────────────────────────────────────────────────
    const apiLogGroup = new logs.LogGroup(this, 'ApiAccessLogs', {
      logGroupName:  '/aws/apigateway/ask-my-docs',
      retention:     logs.RetentionDays.ONE_MONTH,
      encryptionKey,
      removalPolicy: RemovalPolicy.DESTROY,
    });

    const api = new apigateway.RestApi(this, 'Api', {
      restApiName:  'ask-my-docs-api',
      description:  'Ask My Docs query endpoint',
      deployOptions: {
        stageName:               'prod',
        throttlingBurstLimit:    50,
        throttlingRateLimit:     100,
        loggingLevel:            apigateway.MethodLoggingLevel.INFO,
        dataTraceEnabled:        false, // Do not log request/response bodies (PII risk)
        accessLogDestination:    new apigateway.LogGroupLogDestination(apiLogGroup),
        accessLogFormat:         apigateway.AccessLogFormat.jsonWithStandardFields(),
        metricsEnabled:          true,
        tracingEnabled:          true,
      },
      defaultCorsPreflightOptions: {
        allowOrigins: allowedOrigins === '*' ? apigateway.Cors.ALL_ORIGINS : [allowedOrigins],
        allowMethods: ['POST', 'OPTIONS'],
        allowHeaders: ['Content-Type', 'Authorization'],
        maxAge:        Duration.hours(1),
      },
    });

    // Request validator – enforces body schema before Lambda is invoked
    const requestValidator = new apigateway.RequestValidator(this, 'RequestValidator', {
      restApi:          api,
      validateRequestBody: true,
      validateRequestParameters: false,
    });

    const queryModel = new apigateway.Model(this, 'QueryModel', {
      restApi:     api,
      contentType: 'application/json',
      modelName:   'QueryRequest',
      schema: {
        type:     apigateway.JsonSchemaType.OBJECT,
        required: ['question'],
        properties: {
          question: {
            type:      apigateway.JsonSchemaType.STRING,
            minLength: 1,
            maxLength: 500,
          },
          top_k: {
            type:    apigateway.JsonSchemaType.INTEGER,
            minimum: 1,
            maximum: 20,
          },
        },
        additionalProperties: false,
      },
    });

    const queryIntegration = new apigateway.LambdaIntegration(queryLambda, {
      proxy:   true,
      timeout: Duration.seconds(29),
    });

    const queryResource = api.root.addResource('query');
    queryResource.addMethod('POST', queryIntegration, {
      authorizer:        cognitoAuthorizer,
      authorizationType: apigateway.AuthorizationType.COGNITO,
      requestValidator,
      requestModels:     { 'application/json': queryModel },
    });

    // Upload pre-signed URL endpoint (authenticated)
    const uploadResource = api.root.addResource('upload-url');
    const uploadIntegration = new apigateway.LambdaIntegration(
      new lambda.Function(this, 'PresignLambda', {
        functionName: 'ask-my-docs-presign',
        runtime:      lambda.Runtime.PYTHON_3_12,
        handler:      'handler.handler',
        code:         lambda.Code.fromAsset(path.join(__dirname, '../../lambdas/presign')),
        role: (() => {
          const role = new iam.Role(this, 'PresignRole', {
            assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
          });
          role.addToPolicy(new iam.PolicyStatement({
            actions:   ['s3:PutObject'],
            resources: [`${pdfBucket.bucketArn}/*.pdf`],
          }));
          role.addToPolicy(new iam.PolicyStatement({
            actions:   ['logs:CreateLogGroup', 'logs:CreateLogStream', 'logs:PutLogEvents'],
            resources: [`arn:aws:logs:${this.region}:${this.account}:log-group:/aws/lambda/ask-my-docs-presign*`],
          }));
          encryptionKey.grantEncrypt(role);
          return role;
        })(),
        timeout:     Duration.seconds(10),
        environment: { BUCKET_NAME: pdfBucket.bucketName, MAX_FILE_SIZE_MB: String(maxFileSizeMb) },
        tracing:     lambda.Tracing.ACTIVE,
      }),
    );
    uploadResource.addMethod('POST', uploadIntegration, {
      authorizer:        cognitoAuthorizer,
      authorizationType: apigateway.AuthorizationType.COGNITO,
    });

    // ─────────────────────────────────────────────────────────────────────────
    // 11. WAF Web ACL (optional, enabled by default)
    // ─────────────────────────────────────────────────────────────────────────
    if (enableWaf) {
      const webAcl = new wafv2.CfnWebACL(this, 'WebAcl', {
        name:             'ask-my-docs-waf',
        scope:            'REGIONAL',
        defaultAction:    { allow: {} },
        visibilityConfig: {
          sampledRequestsEnabled:   true,
          cloudWatchMetricsEnabled: true,
          metricName:               'AskMyDocsWAF',
        },
        rules: [
          {
            name:     'AWSManagedRulesCommonRuleSet',
            priority: 1,
            overrideAction: { none: {} },
            statement: {
              managedRuleGroupStatement: { vendorName: 'AWS', name: 'AWSManagedRulesCommonRuleSet' },
            },
            visibilityConfig: { sampledRequestsEnabled: true, cloudWatchMetricsEnabled: true, metricName: 'CommonRules' },
          },
          {
            name:     'AWSManagedRulesKnownBadInputsRuleSet',
            priority: 2,
            overrideAction: { none: {} },
            statement: {
              managedRuleGroupStatement: { vendorName: 'AWS', name: 'AWSManagedRulesKnownBadInputsRuleSet' },
            },
            visibilityConfig: { sampledRequestsEnabled: true, cloudWatchMetricsEnabled: true, metricName: 'BadInputs' },
          },
          {
            name:     'RateLimitPerIP',
            priority: 3,
            action:   { block: {} },
            statement: {
              rateBasedStatement: { limit: 300, aggregateKeyType: 'IP' },
            },
            visibilityConfig: { sampledRequestsEnabled: true, cloudWatchMetricsEnabled: true, metricName: 'RateLimit' },
          },
        ],
      });

      new wafv2.CfnWebACLAssociation(this, 'WafAssociation', {
        resourceArn: `arn:aws:apigateway:${this.region}::/restapis/${api.restApiId}/stages/${api.deploymentStage.stageName}`,
        webAclArn:   webAcl.attrArn,
      });
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 12. AOSS Index Custom Resource
    //     Creates the k-NN index at deploy time – no manual step required.
    //     Waits for the collection to be ACTIVE before creating the index.
    // ─────────────────────────────────────────────────────────────────────────
    const indexCreatorRole = new iam.Role(this, 'IndexCreatorRole', {
      assumedBy: new iam.ServicePrincipal('lambda.amazonaws.com'),
    });
    indexCreatorRole.addToPolicy(new iam.PolicyStatement({
      actions:   ['aoss:APIAccessAll'],
      resources: [aossCollection.attrArn],
    }));
    indexCreatorRole.addToPolicy(new iam.PolicyStatement({
      actions:   ['logs:CreateLogGroup', 'logs:CreateLogStream', 'logs:PutLogEvents'],
      resources: [`arn:aws:logs:${this.region}:${this.account}:log-group:/aws/lambda/*`],
    }));
    indexCreatorRole.addToPolicy(new iam.PolicyStatement({
      actions:   ['aoss:ListCollections', 'aoss:BatchGetCollection'],
      resources: ['*'],
    }));

    // Add index creator to the data access policy
    const fullDataAccessPolicy = new opensearchserverless.CfnAccessPolicy(this, 'AossIndexCreatorPolicy', {
      name: 'ask-my-docs-creator',
      type: 'data',
      policy: JSON.stringify([{
        Rules: [{
          ResourceType: 'index',
          Resource:     [`index/${collectionName}/*`],
          Permission:   ['aoss:CreateIndex', 'aoss:UpdateIndex', 'aoss:WriteDocument', 'aoss:ReadDocument', 'aoss:DescribeIndex'],
        }],
        Principal:   [indexCreatorRole.roleArn],
        Description: 'Index creator custom resource',
      }]),
    });
    fullDataAccessPolicy.addDependency(aossCollection);

    const indexCreatorLambda = new lambda.Function(this, 'IndexCreatorLambda', {
      functionName: 'ask-my-docs-index-creator',
      runtime:      lambda.Runtime.PYTHON_3_12,
      handler:      'handler.handler',
      code:         lambda.Code.fromAsset(path.join(__dirname, '../../lambdas/index_creator'), {
        bundling: {
          image:   lambda.Runtime.PYTHON_3_12.bundlingImage,
          command: ['bash', '-c', 'pip install -r requirements.txt -t /asset-output && cp -r . /asset-output'],
        },
      }),
      role:         indexCreatorRole,
      timeout:      Duration.minutes(10),
      environment: {
        COLLECTION_ENDPOINT: aossCollection.attrCollectionEndpoint,
        INDEX_NAME:          collectionName,
        REGION:              this.region,
      },
    });

    const indexCreatorProvider = new cr.Provider(this, 'IndexCreatorProvider', {
      onEventHandler: indexCreatorLambda,
    });

    const indexCreatorResource = new cdk.CustomResource(this, 'IndexCreatorResource', {
      serviceToken: indexCreatorProvider.serviceToken,
      properties: {
        CollectionEndpoint: aossCollection.attrCollectionEndpoint,
        IndexName:          collectionName,
        Timestamp:          Date.now().toString(), // force re-run on stack update
      },
    });
    indexCreatorResource.node.addDependency(fullDataAccessPolicy);

    // ─────────────────────────────────────────────────────────────────────────
    // 13. CloudFormation Outputs
    // ─────────────────────────────────────────────────────────────────────────
    this.apiUrl = new cdk.CfnOutput(this, 'ApiUrl', {
      value:       api.url,
      description: 'API Gateway base URL',
    });

    this.bucketName = new cdk.CfnOutput(this, 'BucketName', {
      value:       pdfBucket.bucketName,
      description: 'PDF upload bucket name',
    });

    this.userPoolId = new cdk.CfnOutput(this, 'UserPoolId', {
      value:       userPool.userPoolId,
      description: 'Cognito User Pool ID',
    });

    this.userPoolClientId = new cdk.CfnOutput(this, 'UserPoolClientId', {
      value:       userPoolClient.userPoolClientId,
      description: 'Cognito User Pool Client ID',
    });

    new cdk.CfnOutput(this, 'CollectionEndpoint', {
      value:       aossCollection.attrCollectionEndpoint,
      description: 'OpenSearch Serverless collection endpoint',
    });

    // Apply removal policy tag for easy identification
    cdk.Tags.of(this).add('Project',     'ask-my-docs');
    cdk.Tags.of(this).add('Environment', 'demo');
    cdk.Tags.of(this).add('ManagedBy',   'CDK');
  }
}
